### ISSUE TITLE
Info on Text Viewer

### ISSUE THREAD

**Issue by echads** [BadLuckBurt/dfu-worlddata-editor#3]
It looks like the Text Viewer is a tool to help in writing quests? Is it meant to be a quick reference? How should we use this?
![image](https://user-images.githubusercontent.com/37284476/144774862-6319f981-2eec-4413-80a7-6320c6f61374.png)

**Comment by BadLuckBurt** [comment]
Hi Echads,

It is indeed meant to just be a quick reference. It can't be used to edit or add anything, I just made it so I would have all the text in one place and could take a look at unused texts.

You probably already know about it but TheLacus (https://github.com/rossipaolo/vscode-dftemplate) made a great VS Code plugin that helps with quest creation, that might help you more than this viewer.

**Comment by echads** [comment]
I did find the Text Viewer easy on the eyes. Thank you.
